name: CloudNetAPI
version: ${project.version}
author: CloudNetService
website: https://cloudnetservice.eu/
description: CloudNet Interface for the Central server

main: eu.cloudnetservice.cloudnet.v2.bridge.BukkitBootstrap

softdepend: [Vault, VaultAPI]

commands:
  cloudserver:
    aliases: ["cs"]
