name: CloudNet Build

on: [create, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '12']

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build with Maven
      run: mvn clean test package
    - name: Release ZIP
      run: |
        mkdir -p temp;
        cp -r .template/* temp/;
        cp cloudnet-master/target/CloudNet-Master.jar temp/CloudNet-Master/;
        cp cloudnet-wrapper/target/CloudNet-Wrapper.jar temp/CloudNet-Wrapper/;
    - uses: actions/upload-artifact@master
      with:
        name: CloudNet-V2
        path: temp/
